name: Release beta

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Name of next version (ie 2.2.0-beta.2)'
        required: true

      prerelease:
        description: 'Pre-release? (true/false)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: set up Ruby for fastlane
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install bundle
        run: bundle install

      - name: Set Git credentials
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Put environment variables in .env file and create key store
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/keystore.jks

          echo "VERSION_NAME=${{ github.event.inputs.version_name }}" >> app/.env
          echo "STORE_PASSWORD=$KEYSTORE_STORE_PASSWORD" >> app/.env
          echo "KEY_ALIAS=$KEYSTORE_KEY_ALIAS" >> app/.env
          echo "KEY_PASSWORD=$KEYSTORE_KEY_PASSWORD" >> app/.env
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest

      - name: Build apk with fastlane
        run: bundle exec fastlane beta

      - name: set debug apk name env
        run: echo "APK_NAME_DEBUG=$(basename app/build/outputs/apk/debug/*.apk .apk)" >> $GITHUB_ENV

      - name: Upload to Discord
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_BUILD_STATUS_WEBHOOK }}
        with:
          args: app/build/outputs/apk/debug/${{ env.APK_NAME_DEBUG }}.apk

      - name: set release apk name env
        run: echo "APK_NAME_RELEASE=$(basename app/build/outputs/apk/release/*.apk .apk)" >> $GITHUB_ENV

      - name: Upload to Discord
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_BUILD_STATUS_WEBHOOK }}
        with:
          args: app/build/outputs/apk/release/${{ env.APK_NAME_RELEASE }}.apk

